import type { Item, Category, Tag, WishItem } from '@/types';

const today = new Date();
const daysAgo = (n: number) =>
  new Date(today.getTime() - n * 86_400_000).toISOString();

export const seedCategories: Category[] = [
  { id: 'electronics', name: '电子设备', iconName: '3d_handphone', order: 1 },
  { id: 'clothing', name: '服饰', iconName: 'Coat', order: 2 },
  { id: 'beauty', name: '美妆护肤', iconName: 'Bb_cream', order: 3 },
  { id: 'furniture', name: '家具家居', iconName: 'Bed', order: 4 },
  { id: 'appliance', name: '家电', iconName: 'Air_conditioner', order: 5 },
  { id: 'sport', name: '运动户外', iconName: 'Backpack', order: 6 },
  { id: 'vehicle', name: '出行交通', iconName: 'Bicycle', order: 7 },
  { id: 'others', name: '其他', iconName: 'toolbox', order: 99 },
];

export const seedTags: Tag[] = [
  { id: 't_daily', name: '每天用', color: '#b5f23d' },
  { id: 't_work', name: '工作', color: '#5ac8fa' },
  { id: 't_gift', name: '礼物', color: '#ff9500' },
  { id: 't_pro', name: 'Pro 装备', color: '#af52de' },
];

export const seedItems: Item[] = [
  {
    id: 'demo-1',
    name: 'iPhone 15 Pro',
    iconName: '3d_handphone',
    categoryId: 'electronics',
    tagIds: ['t_daily', 't_work', 't_pro'],
    price: 8999,
    currency: 'CNY',
    purchaseDate: daysAgo(420),
    targetDailyCost: 10,
    usageCount: 1500,
    status: 'inUse',
    isFavorite: true,
    isPinned: true,
    notes: '主力机',
    createdAt: daysAgo(420),
    updatedAt: daysAgo(2),
  },
  {
    id: 'demo-2',
    name: 'AirPods Pro 2',
    iconName: '3d_headphone',
    categoryId: 'electronics',
    tagIds: ['t_daily'],
    price: 1899,
    currency: 'CNY',
    purchaseDate: daysAgo(720),
    targetDailyCost: 3,
    usageCount: 700,
    status: 'inUse',
    isFavorite: false,
    isPinned: false,
    createdAt: daysAgo(720),
    updatedAt: daysAgo(10),
  },
  {
    id: 'demo-3',
    name: 'MacBook Pro 14',
    iconName: '3d_video',
    categoryId: 'electronics',
    tagIds: ['t_work', 't_pro'],
    price: 16999,
    currency: 'CNY',
    purchaseDate: daysAgo(900),
    targetDailyCost: 30,
    usageCount: 850,
    status: 'inUse',
    isFavorite: true,
    isPinned: true,
    createdAt: daysAgo(900),
    updatedAt: daysAgo(1),
  },
  {
    id: 'demo-4',
    name: 'Nike Air Max',
    iconName: 'Boots',
    categoryId: 'clothing',
    tagIds: ['t_daily'],
    price: 999,
    currency: 'CNY',
    purchaseDate: daysAgo(180),
    targetDailyCost: 5,
    usageCount: 90,
    status: 'inUse',
    isFavorite: false,
    isPinned: false,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(3),
  },
  {
    id: 'demo-5',
    name: 'Aēsop 香水',
    iconName: 'Argan_oil',
    categoryId: 'beauty',
    tagIds: ['t_gift'],
    price: 1280,
    currency: 'CNY',
    purchaseDate: daysAgo(90),
    targetDailyCost: 12,
    usageCount: 80,
    status: 'inUse',
    isFavorite: true,
    isPinned: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },
  {
    id: 'demo-6',
    name: 'IKEA POÄNG 椅子',
    iconName: 'Chair',
    categoryId: 'furniture',
    tagIds: ['t_daily'],
    price: 599,
    currency: 'CNY',
    purchaseDate: daysAgo(1100),
    targetDailyCost: 1,
    usageCount: 1100,
    status: 'inUse',
    isFavorite: false,
    isPinned: false,
    createdAt: daysAgo(1100),
    updatedAt: daysAgo(15),
  },
  {
    id: 'demo-7',
    name: '索尼相机',
    iconName: 'Camera_icon',
    categoryId: 'electronics',
    tagIds: ['t_pro'],
    price: 12000,
    currency: 'CNY',
    purchaseDate: daysAgo(600),
    targetDailyCost: 40,
    usageCount: 50,
    status: 'idle',
    isFavorite: false,
    isPinned: false,
    notes: '最近不太用',
    createdAt: daysAgo(600),
    updatedAt: daysAgo(60),
  },
  {
    id: 'demo-8',
    name: '旧款 iPad mini',
    iconName: '3d_video',
    categoryId: 'electronics',
    tagIds: [],
    price: 3500,
    currency: 'CNY',
    purchaseDate: daysAgo(1500),
    soldDate: daysAgo(20),
    soldPrice: 800,
    usageCount: 1400,
    status: 'sold',
    isFavorite: false,
    isPinned: false,
    createdAt: daysAgo(1500),
    updatedAt: daysAgo(20),
  },
];

export const seedWish: WishItem[] = [
  {
    id: 'w-1',
    name: 'Vision Pro',
    iconName: '3d_video',
    price: 29999,
    notes: '等下一代',
    createdAt: daysAgo(30),
  },
  {
    id: 'w-2',
    name: '咖啡机',
    iconName: 'Cooker_hood',
    price: 4500,
    createdAt: daysAgo(10),
  },
];
